# docker-compose.yml (Updated to use .env file)

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      # These now read from the .env file
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  backend:
    build: ./backend-service
    restart: always
    ports:
      - '3000:3000'
    environment:
      # This constructs the database URL using variables from the .env file
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      PORT: 3000
      NODE_ENV: 'development'
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  frontend:
    build: ./frontend-service
    restart: always
    ports:
      - '8080:8080'
    environment:
      BACKEND_API_URL: http://backend:3000
    depends_on:
      - backend

volumes:
  db-data: